name: Update playlist

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update playlist
        run: |
          git config user.name "PlaylistBot" || true
          git config user.email "86968636+mdy175@users.noreply.github.com" || true
          python3 ./make_playlist.py
          git add .
          git commit --quiet -m "Update Playlist (GitHub Actions)"
          git push -f origin master
